"""Update UserRole enum to OWNER, MANAGER, COUNTER

Revision ID: 4652eaff16da
Revises: ea64abb2d3bf
Create Date: 2025-12-14 20:08:02.418771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4652eaff16da'
down_revision: Union[str, None] = 'ea64abb2d3bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

