"""Add Business and UserBusiness models

Revision ID: 609b4a493af9
Revises: f91b047bd72a
Create Date: 2025-12-14 18:49:27.809648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '609b4a493af9'
down_revision: Union[str, None] = 'f91b047bd72a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('CLINIC', 'HOSPITAL', 'SALON', 'SPA', 'FITNESS', 'OTHER', name='businesstype'), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_id'), 'businesses', ['id'], unique=False)
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=False)
    op.create_table('user_businesses',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'STAFF', name='userrole'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'business_id', name='uq_user_business')
    )
    op.create_index(op.f('ix_user_businesses_business_id'), 'user_businesses', ['business_id'], unique=False)
    op.create_index(op.f('ix_user_businesses_id'), 'user_businesses', ['id'], unique=False)
    op.create_index(op.f('ix_user_businesses_user_id'), 'user_businesses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_businesses_user_id'), table_name='user_businesses')
    op.drop_index(op.f('ix_user_businesses_id'), table_name='user_businesses')
    op.drop_index(op.f('ix_user_businesses_business_id'), table_name='user_businesses')
    op.drop_table('user_businesses')
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_id'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###

