"""Add Customer, Counter, and QueueItem models

Revision ID: 670809e1b04f
Revises: 4652eaff16da
Create Date: 2025-12-15 00:30:24.770208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670809e1b04f'
down_revision: Union[str, None] = '4652eaff16da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('whatsapp_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_firstname'), 'customers', ['firstname'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_lastname'), 'customers', ['lastname'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_table('counters',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counters_business_id'), 'counters', ['business_id'], unique=False)
    op.create_index(op.f('ix_counters_id'), 'counters', ['id'], unique=False)
    op.create_table('queue_items',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('counter_id', sa.UUID(), nullable=True),
    sa.Column('queue_type', sa.Enum('NORMAL', 'EMERGENCY', name='queuetype', native_enum=False), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'NOTIFIED', 'SERVED', 'MISSED', 'CANCELLED', name='queueitemstatus', native_enum=False), nullable=False),
    sa.Column('miss_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['counter_id'], ['counters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_items_business_id'), 'queue_items', ['business_id'], unique=False)
    op.create_index(op.f('ix_queue_items_counter_id'), 'queue_items', ['counter_id'], unique=False)
    op.create_index(op.f('ix_queue_items_customer_id'), 'queue_items', ['customer_id'], unique=False)
    op.create_index(op.f('ix_queue_items_id'), 'queue_items', ['id'], unique=False)
    op.create_index(op.f('ix_queue_items_position'), 'queue_items', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queue_items_position'), table_name='queue_items')
    op.drop_index(op.f('ix_queue_items_id'), table_name='queue_items')
    op.drop_index(op.f('ix_queue_items_customer_id'), table_name='queue_items')
    op.drop_index(op.f('ix_queue_items_counter_id'), table_name='queue_items')
    op.drop_index(op.f('ix_queue_items_business_id'), table_name='queue_items')
    op.drop_table('queue_items')
    op.drop_index(op.f('ix_counters_id'), table_name='counters')
    op.drop_index(op.f('ix_counters_business_id'), table_name='counters')
    op.drop_table('counters')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_lastname'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_firstname'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###

