"""Add Notification model for WhatsApp notifications

Revision ID: aa52c5bcf205
Revises: c11e8e01f9c5
Create Date: 2025-12-15 00:56:21.783992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa52c5bcf205'
down_revision: Union[str, None] = 'c11e8e01f9c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('queue_item_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('WHATSAPP', 'SMS', 'EMAIL', name='notificationtype', native_enum=False), nullable=False),
    sa.Column('recipient_phone', sa.String(), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=True),
    sa.Column('message_template', sa.String(), nullable=True),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'DELIVERED', 'READ', name='notificationstatus', native_enum=False), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_item_id'], ['queue_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_business_id'), 'notifications', ['business_id'], unique=False)
    op.create_index(op.f('ix_notifications_customer_id'), 'notifications', ['customer_id'], unique=False)
    op.create_index(op.f('ix_notifications_external_id'), 'notifications', ['external_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_queue_item_id'), 'notifications', ['queue_item_id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_phone'), 'notifications', ['recipient_phone'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_phone'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_queue_item_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_external_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_customer_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_business_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###

