"""Add Customer, Counter, and QueueItem models

Revision ID: c11e8e01f9c5
Revises: 670809e1b04f
Create Date: 2025-12-15 00:33:07.560605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c11e8e01f9c5'
down_revision: Union[str, None] = '670809e1b04f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_counters_name'), 'counters', ['name'], unique=False)
    op.add_column('customers', sa.Column('business_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_customers_business_id'), 'customers', ['business_id'], unique=False)
    op.create_foreign_key(None, 'customers', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_queue_items_queue_type'), 'queue_items', ['queue_type'], unique=False)
    op.create_index(op.f('ix_queue_items_status'), 'queue_items', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queue_items_status'), table_name='queue_items')
    op.drop_index(op.f('ix_queue_items_queue_type'), table_name='queue_items')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_business_id'), table_name='customers')
    op.drop_column('customers', 'business_id')
    op.drop_index(op.f('ix_counters_name'), table_name='counters')
    # ### end Alembic commands ###

