"""Change all id columns from Integer to UUID

Revision ID: ea64abb2d3bf
Revises: 0dc637c56d72
Create Date: 2025-12-14 19:19:41.135817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea64abb2d3bf'
down_revision: Union[str, None] = '0dc637c56d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop existing tables and recreate with UUID
    # This is safe for fresh databases. For production with data, you'd need a more complex migration.
    op.drop_table('user_businesses')
    op.drop_table('businesses')
    op.drop_table('users')
    
    # Drop enum types if they exist
    op.execute("DROP TYPE IF EXISTS userrole")
    op.execute("DROP TYPE IF EXISTS businesstype")
    
    # Recreate users table with UUID
    op.create_table('users',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('password_hash', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    
    # Recreate businesses table with UUID
    op.create_table('businesses',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('timezone', sa.String(), nullable=False, server_default='UTC'),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
    )
    op.create_index('ix_businesses_id', 'businesses', ['id'], unique=False)
    op.create_index('ix_businesses_name', 'businesses', ['name'], unique=False)
    
    # Recreate user_businesses table with UUID
    op.create_table('user_businesses',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('business_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('role', sa.String(), nullable=False, server_default='staff'),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
        sa.UniqueConstraint('user_id', 'business_id', name='uq_user_business')
    )
    op.create_index('ix_user_businesses_id', 'user_businesses', ['id'], unique=False)
    op.create_index('ix_user_businesses_user_id', 'user_businesses', ['user_id'], unique=False)
    op.create_index('ix_user_businesses_business_id', 'user_businesses', ['business_id'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_businesses', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_businesses', 'role',
               existing_type=sa.Enum('OWNER', 'STAFF', name='userrole', native_enum=False),
               type_=postgresql.ENUM('OWNER', 'STAFF', name='userrole'),
               existing_nullable=False)
    op.alter_column('user_businesses', 'business_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_businesses', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('businesses', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('businesses', 'type',
               existing_type=sa.Enum('CLINIC', 'HOSPITAL', 'SALON', 'SPA', 'FITNESS', 'OTHER', name='businesstype', native_enum=False),
               type_=postgresql.ENUM('CLINIC', 'HOSPITAL', 'SALON', 'SPA', 'FITNESS', 'OTHER', name='businesstype'),
               existing_nullable=False)
    # ### end Alembic commands ###

